---
kind: Template
apiVersion: v1
metadata:
  name: mysql-schedule-backup-to-s3-pvc
  annotations:
    openshift.io/display-name: "MySQL Schedule backup to S3 or PVC"
    description: Schedule backup from MySQL database to S3 services, or to PVC
    tags: mysql,s3aws,pvc
    iconClass: icon-mysql-database
message: |-
  ${NAME} has been created in your project.
labels:
  template: mysql-schedule-backup-to-s3-pvc
  app: "wordpress"
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${NAME}-s3-secret"
    labels:
      app: "wordpress-${NAME}"
  stringData:
    aws-access-key-id: "${AWS_ACCESS_KEY_ID}"
    aws-secret-access-key: "${AWS_SECRET_ACCESS_KEY}"
- kind: CronJob
  apiVersion: batch/v1beta1
  metadata:
    name: "${NAME}"
  spec:
    schedule: "${CRON_TIME}"
    jobTemplate:
      spec:
        template:
          metadata:
            name: "${NAME}"
            labels:
              appName: "wordpress-${NAME}"
          spec:
            containers:
            - name: backup
              image: "${IMAGE}"
              imagePullPolicy: Always
              command: ["/bin/sh"]
              args: ["/var/lib/mysql/bin/mysql_s3_backup.sh"]
              volumeMounts:
              - mountPath: "/data/backup"
                name: "${STORAGE_PVC_BACKUP}-data"
              env:
              - name: MYSQL_HOST
                value: "${DATABASE_HOST}"
              - name: MYSQL_NAME
                value: "${DATABASE_NAME}"
              - name: MYSQL_PORT
                value: "${DATABASE_PORT}"
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: "${DATABASE_SECRET_NAME}"
                    key: database-password
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: "${DATABASE_SECRET_NAME}"
                    key: database-user
              - name: METHODS
                value: "${METHODS}"
              - name: DAYTODEL
                value: "${DAYTODEL}"
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: "${NAME}-s3-secret"
                    key: aws-access-key-id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: "${NAME}-s3-secret"
                    key: aws-secret-access-key
              - name: AWS_BUCKET
                value: "${AWS_BUCKET_NAME}"
              - name: LOCATION_STORAGE
                value: "${LOCATION_PVC_BACKUP}"
            volumes:
            - name: "${STORAGE_PVC_BACKUP}-data"
              persistentVolumeClaim:
                claimName: ${STORAGE_PVC_BACKUP}
            restartPolicy: OnFailure
parameters:
- name: NAME
  displayName: Name of schedule job
  required: true
  value: bn-academy-stage-backup-db-job
- name: IMAGE
  displayName: Name of image
  required: true
  value: docker-registry.default.svc:5000/bn-academy-stage/job-container
- name: METHODS
  displayName: Backup method
  description: 'values: "s3", "pvc", "s3,pvc", "none"'
  required: true
  value: pvc
- name: DATABASE_HOST
  displayName: Database Host
  required: true
- name: DATABASE_PORT
  displayName: Database Port
  required: true
  value: '3306'
- name: DATABASE_NAME
  displayName: Database Name
  required: true
  value: wordpress
- name: DATABASE_SECRET_NAME
  displayName: Name of Secret where database-password and database-user stored
  required: true
  value: bonniernews-academy-stage
- name: CRON_TIME
  displayName: When to run the backup cronjob
  description: Cron time string define when backup start (Ex 0 3 * * * - Run at 3AM every day)
  required: true
  value: 0 3 * * *
- name: DAYTODEL
  displayName: Day duration
  description: Day duration to keep backup file
  required: false
  value: '10'
- name: STORAGE_PVC_BACKUP
  displayName: Backup Storage (require for PVC method)
  description: The Pesistent Volumne Claim where backup files locate
  required: false
  value: bn-academy-stage-backup-storage
- name: LOCATION_PVC_BACKUP
  displayName: Backup folder name (require for PVC method)
  description: Directory's name of backup file
  required: false
  value: wordpress_backup
- name: AWS_ACCESS_KEY_ID
  displayName: Amazon WebService Key ID (require for AWS S3 method)
  required: false
- name: AWS_SECRET_ACCESS_KEY
  displayName: Amazon WebService Secret Key (require for AWS S3 method)
  required: false
- name: AWS_BUCKET_NAME
  displayName: Amazon WebService Bucket Name (require for AWS S3 method)
  required: false
  value: s3://example